"""empty message

Revision ID: 24674d14e611
Revises: 7e0831937853
Create Date: 2022-09-13 09:55:15.174163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24674d14e611'
down_revision = '7e0831937853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('mimetype', sa.Text(), nullable=False))
    op.alter_column('piece', 'image',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_unique_constraint(None, 'piece', ['image'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'piece', type_='unique')
    op.alter_column('piece', 'image',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('piece', 'mimetype')
    # ### end Alembic commands ###
