"""empty message

Revision ID: 7e0831937853
Revises: 7c29efcddec3
Create Date: 2022-09-12 18:31:58.687955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0831937853'
down_revision = '7c29efcddec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('street_address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('city', sa.VARCHAR(length=10), nullable=False),
    sa.Column('state', sa.VARCHAR(length=10), nullable=False),
    sa.Column('country', sa.VARCHAR(length=10), nullable=False),
    sa.Column('zip_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('piece')
    # ### end Alembic commands ###
